### ISSUE TITLE
Unable to reproduce pre-processing for HAR, Sleep-EDF, Epilepsy datasets

### ISSUE THREAD

**Issue by gorold** [emadeldeen24/TS-TCC#1]
Hi, thanks for releasing your code! I am trying to reproduce the results from the paper, as well as extend to other datasets, but run into some problems due to insufficient information to recreate the datasets.

1. Code for pre-processing the HAR dataset is missing. Furthermore, the HAR dataset linked in the README.md comes with 561 dimensions, whereas the config file indicates 9 input channels.
2. Code for pre-processing the Sleep-EDF dataset does not result in files which match the description in the README.md nor the dataloader code.
3. Code for pre-processing the Epilepsy dataset only results in train.pt and test.pt, missing a val.pt file as indicated in the README.md and dataloader code.
4. Also, is it possible to include a requirements.txt file, because it seems that some libraries being used are not backward compatible. The latest version of mne does not have scaling_time as an argument to raw.to_data_frame.
https://github.com/emadeldeen24/TS-TCC/blob/5c5efa7b695b7425d3ded4a93a7a6010102aa9b0/data_preprocessing/sleep-edf/preprocess_sleep_edf.py#L90

Thank you!

**Comment by gorold** [comment]
Furthermore, it seems that the sleep-edf data pre-processing code does not results in files which match the description in the README. Hope that you are able to release the data pre-processing code which matches the dataloader code.

Also, is it possible to include a requirements.txt file, because it seems that some libraries being used are not backward compatible.
https://github.com/emadeldeen24/TS-TCC/blob/5c5efa7b695b7425d3ded4a93a7a6010102aa9b0/data_preprocessing/sleep-edf/preprocess_sleep_edf.py#L90
The latest version of mne does not have scaling_time as an argument to raw.to_data_frame.

Thank you for your time!

**Comment by emadeldeen24** [comment]
Hello,
thank you for reaching me out and reporting these issues. 

I solved all your issues ... please check the updated version of README file as well as preprocessing files.

**Comment by Alan-77** [comment]
Hi @emadeldeen24 

The Sleep EDF dataset contains two folders, i.e., sleep-cassette and sleep-telemetry. I am wondering which folder you used exactly, or you use the data from both two folders. Thanks.

**Comment by emadeldeen24** [comment]
I used sleep-cassette .. more specifically [these files](https://gist.github.com/emadeldeen24/a22691e36759934e53984289a94cb09b) .
