### ISSUE TITLE
A question about your new work

### ISSUE THREAD

**Issue by Sample-design-alt** [emadeldeen24/TS-TCC#12]
Hello Emadeldeen,
Recently I noticed your new paper---Self-supervised Contrastive Representation Learning for Semi-supervised Time-Series
Classification on arxiv.
Could you share the TS-TCC code and other methods (e.g., simclr, CPC) also?

**Comment by emadeldeen24** [comment]
Hello @Sample-design-alt,
thank you for your interest in our work.
This repo is already the implementation of TS-TCC. 
The other methods are already public. For example, these are the implementations of [simclr](https://github.com/sthalles/SimCLR), and [CPC](https://github.com/jefflai108/Contrastive-Predictive-Coding-PyTorch/blob/master/src/model/model.py).
