### ISSUE TITLE
there might be code error for augmentation?

### ISSUE THREAD

**Issue by sinsa902** [emadeldeen24/TS-TCC#17]
In strong augmentation, is it correct that pat[0,warp]?
I think pat[:,warp] should be correct.
Could you check below code?

    for i, pat in enumerate(x):
        if num_segs[i] > 1:
            if seg_mode == "random":
                split_points = np.random.choice(x.shape[2] - 2, num_segs[i] - 1, replace=False)
                split_points.sort()
                splits = np.split(orig_steps, split_points)
            else:
                splits = np.array_split(orig_steps, num_segs[i])
            warp = np.concatenate(np.random.permutation(splits)).ravel()
            ret[i] = pat[0,warp]
        else:
            ret[i] = pat
    return torch.from_numpy(ret)

**Comment by emadeldeen24** [comment]
It should be correct according to my settings.

**Comment by Blues-He** [comment]
@sinsa902 in my opinion,maybe you are right.because it only use one channel.or Maybe I missed something.
