### ISSUE TITLE
Obtaining labels on a completly unsupervised dataset

### ISSUE THREAD

**Issue by protti** [emadeldeen24/TS-TCC#21]
Hi @emadeldeen24, I found this project interesting, but I still need to understand completely how I can obtain labels on the fully unsupervised dataset. Once I've completed the training in self-supervised mode, how can I get the predictions for each time series provided in the input? 
I've seen that you use Fine-tuning or the linear classifier, but they require some data labels in input. How can I use a completely unsupervised version?

**Comment by emadeldeen24** [comment]
Hi @protti,
with self-supervised learning, you learn general representations about data. You can't use those to obtain labels. To obtain labels, you need a classifier that can produce the output probabilities according to the number of classes, which is usually absent in the SSL training. Therefore, we train a linear classifier on top of the SSL-learned encoder with some (few) labeled data.
