### ISSUE TITLE
data augment

### ISSUE THREAD

**Issue by 1805446158** [emadeldeen24/TS-TCC#22]
def scaling(x, sigma=1.1):
    # https://arxiv.org/pdf/1706.00527.pdf
    factor = np.random.normal(loc=2., scale=sigma, size=(x.shape[0], x.shape[2]))
    ai = []
    for i in range(x.shape[1]):
        xi = x[:, i, :]
        ai.append(np.multiply(xi, factor[:, :])[:, np.newaxis, :])
    return np.concatenate((ai), axis=1)

In this paper, weak augmentation is a
jitter-and-scale strategy. Specifically, we add random variations to the signal and scale up its magnitude. But why no jitter in weak augment.

**Comment by emadeldeen24** [comment]
The jitter is added by the `np.random.normal` function.
