### ISSUE TITLE
Can not repeat FD dataset preprocess

### ISSUE THREAD

**Issue by SHIELD-SKY** [emadeldeen24/TS-TCC#23]
Mat_0(k,a,:)=vib_0(i:i+wind_size);
            
What is the value of wind_size?

I guess wind_size == sample_len?

However, after that, i see this error:

`>> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> Error using reshape
Number of elements must not change. Use [] as one of the size inputs to
automatically calculate the appropriate size for that dimension.
`

**Comment by emadeldeen24** [comment]
@mohamedr002 Please advise.

**Comment by mohamedr002** [comment]
Hi, sorry for this, it seems that it wasn't the final file that I have uploaded, please use the following. 
`            Mat_0(k,a,:)=vib_0(i:i+sample_len-1);`

Also, if you want to use directly the FD data proceed version you can find it here: 
https://researchdata.ntu.edu.sg/dataset.xhtml?persistentId=doi:10.21979/N9/PU85XN

**Comment by SHIELD-SKY** [comment]
Thanks for your reply.  I will try the code again.
