### ISSUE TITLE
Something wrong with the code when i use self-supervised mode

### ISSUE THREAD

**Issue by kkizjw** [emadeldeen24/TS-TCC#33]
when i use self-supervised mode, the code report "setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part." in the line of "warp = np.concatenate(np.random.permutation(splits)).ravel()" in "augmentation" .How should i change the code to run it successfully?

**Comment by emadeldeen24** [comment]
Refer to this issue https://github.com/emadeldeen24/TS-TCC/issues/27
