### ISSUE TITLE
About Unsupervised Downstream Tasks

### ISSUE THREAD

**Issue by kke12580** [emadeldeen24/TS-TCC#34]
Dear author, thank you for your contribution. I’ve been using your code and noticed that it seems unsuitable for unsupervised downstream tasks. Specifically, my downstream task involves using an autoencoder for binary class anomaly detection. If it’s feasible, could you inform me which part of the code should be modified?

**Comment by emadeldeen24** [comment]
you can use the autoencoder itself to perform the pretraining by doing an unsupervised reconstruction task (you can follow MAE works). Then use it for the downstream task.
