### ISSUE TITLE
Augmentations

### ISSUE THREAD

**Issue by kuwar81523** [emadeldeen24/TS-TCC#5]
Why we are doing augmentation on the whole dataset only once and we are using this dataset during the self supervised training?
Shouldn't we augment the dataset at each epoch?

**Comment by emadeldeen24** [comment]
Usually it is done in the beginning to make training faster.

**Comment by kuwar81523** [comment]
But we need to do augmentation at each epoch otherwise our data would get fixed on the initial augmentations; in self supervised training shouldn't we augment at each epoch? Sorry let me know if I am missing something here :)

**Comment by kuwar81523** [comment]
As we are initializing the dataset class only once; we are using augmentation only once.But we need to do augmentation at each epoch otherwise our data would get fixed on the initial augmentations; in self supervised training shouldn't we augment at each epoch? Sorry let me know if I am missing something here :)

**Comment by emadeldeen24** [comment]
I'm not sure if it will make a difference, but you can test and let me know.

**Comment by kuwar81523** [comment]
sure
