### ISSUE TITLE
Evaluation Process

### ISSUE THREAD

**Issue by kuwar81523** [emadeldeen24/TS-TCC#6]
We have used the same dataset and code as shared and haven't changed any configs; but in the linear evaluation experiment we are not getting the results near to the one shown in the paper; have you used any other evaluation process to get the results as presented in the paper like k cross validation or any change in the number of epochs pretrained?

**Comment by emadeldeen24** [comment]
> have you used any other evaluation process to get the results as presented in the paper like k cross validation or any change in the number of epochs pretrained?

No.

**Comment by emadeldeen24** [comment]
If you still have an issue reproducing the results, you can drop me an email with more details about your experiments.
