### ISSUE TITLE
time series forecasting

### ISSUE THREAD

**Issue by zxhjames** [emadeldeen24/TS-TCC#7]
Hi, great job! can this model be used for time series forecasting?How's the effect

**Comment by emadeldeen24** [comment]
I didn't test on time series forecasting applications. 
However, self-supervised contrastive learning is used here to pretrain the encoder network from the unlabeled data, regardless the downstream task. You can just plug the downstream task you want afterwards by adding the suitable module (i.e., classification, forecasting, anomaly detection, etc.).

**Comment by zxhjames** [comment]
thanks a lot, I will try to test it
